export const  REMOVE_LAST_LIST_ITEM = 'REMOVE_LAST_LIST_ITEM',
              REMOVE_FIRST_LIST_ITEM = 'REMOVE_FIRST_LIST_ITEM',
              REPLACE_LAST_ITEM_TO_START = 'REPLACE_LAST_ITEM_TO_START',
              REPLACE_FIRST_ITEM_TO_END = 'REPLACE_FIRST_ITEM_TO_END';